'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const Engine=globalThis.CompatibilityEngine;
const MAX_FILES=3000, MAX_TOTAL=70*1024*1024, MAX_FILE=2.5*1024*1024;
const state={game:'hoi4',filesA:[],filesB:[],a:new Map(),b:new Map(),conflicts:[],filter:'all',search:'',loadOrder:'unknown'};
function fmt(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`;}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function readEntry(file){return file.text().then(text=>({text,path:Engine.relativeProjectPath(file),bytes:file.size}));}
function select(side,files){const usable=files.filter(Engine.supportedFile).slice(0,MAX_FILES);state[side==='a'?'filesA':'filesB']=usable;const total=usable.reduce((n,f)=>n+f.size,0);$(`#status${side.toUpperCase()}`).textContent=usable.length?`${usable.length} text files · ${fmt(total)}`:'Nothing selected';updateReady();}
function updateReady(){const ok=state.filesA.length&&state.filesB.length;$('#compatRun').disabled=!ok;$('#compatReady').textContent=ok?'Two mods ready to compare.':'Choose both mod root folders.';$('#compatReadyDetail').textContent=ok?'Comparison stays on this device.':'Use complete mod roots for the most reliable result.';}
async function load(files,map,label,start,end){map.clear();let total=files.reduce((n,f)=>n+f.size,0);if(total>MAX_TOTAL)throw new Error(`${label} is larger than ${fmt(MAX_TOTAL)}.`);let done=0;for(const f of files){if(f.size<=MAX_FILE){try{const e=await readEntry(f);map.set(e.path,e);}catch{}}done++;if(done%50===0||done===files.length){const p=start+(done/Math.max(1,files.length))*(end-start);setProgress(p,`Reading ${label}: ${done}/${files.length}`);await new Promise(r=>setTimeout(r,0));}}}
function setProgress(p,t){$('#compatProgress').classList.remove('hidden');$('#compatProgressBar').style.width=`${Math.round(p)}%`;$('#compatProgressText').textContent=t;}
function finishProgress(){$('#compatProgress').classList.add('hidden');$('#compatProgressBar').style.width='0%';}
async function run(){try{state.loadOrder=$('#loadOrder').value;setProgress(2,'Preparing…');await load(state.filesA,state.a,'Mod A',4,42);await load(state.filesB,state.b,'Mod B',44,82);setProgress(88,'Comparing IDs, paths and replace_path…');state.conflicts=Engine.compare(state.a,state.b,state.game,state.loadOrder);await new Promise(r=>setTimeout(r,0));setProgress(98,'Building report…');renderSummary();render();finishProgress();$('#compatResults').classList.remove('hidden');$('#compatResults').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){finishProgress();$('#compatReady').textContent=e.message;$('#compatReadyDetail').textContent='Reduce the folder selection and try again.';}}
function counts(){const c={error:0,warning:0,info:0,path:0,id:0};for(const x of state.conflicts){c[x.severity]++;if(x.kind==='path')c.path++;if(x.kind==='id')c.id++;}return c;}
function renderSummary(){const c=counts();$('#compatHigh').textContent=c.error;$('#compatReview').textContent=c.warning;$('#compatInfo').textContent=c.info;$('#compatSharedPaths').textContent=c.path;$('#compatTitle').textContent=c.error?'High-confidence conflicts found':c.warning?'Review compatibility overlaps':'No supported conflicts found';$('#compatSubtitle').textContent=`${state.game==='hoi4'?'Hearts of Iron IV':'Victoria 3'} · ${state.a.size} Mod A files · ${state.b.size} Mod B files`;const top=state.conflicts.filter(x=>x.severity!=='info').slice(0,5);$('#compatStart').classList.toggle('hidden',!top.length);$('#compatStartList').innerHTML=top.map(x=>`<li><strong>${esc(x.title)}</strong>${x.pathA?` — ${esc(x.pathA)}`:''}</li>`).join('');}
function visible(){const q=state.search.toLowerCase();return state.conflicts.filter(x=>state.filter==='all'||x.severity===state.filter).filter(x=>!q||`${x.title} ${x.detail} ${x.pathA||''} ${x.pathB||''} ${x.category}`.toLowerCase().includes(q));}
function render(){const list=$('#compatList'),items=visible();list.innerHTML='';$('#compatEmpty').classList.toggle('hidden',items.length>0);for(const x of items.slice(0,600)){const card=document.createElement('article');card.className='finding';const label=x.severity==='error'?'high conflict':x.severity==='warning'?'review':'info';card.innerHTML=`<div class="finding-main"><div class="finding-top"><div class="finding-title-wrap"><span class="severity-mark ${x.severity}"></span><div><h3>${esc(x.title)}</h3><div class="finding-meta">${esc(x.category)} · ${esc(x.confidence)} confidence</div></div></div><div class="finding-badges"><span class="badge ${x.severity==='error'?'root':''}">${label}</span></div></div><p class="finding-explanation">${esc(x.detail)}</p><div class="compat-paths">${x.pathA?`<span><strong>Mod A</strong>${esc(x.pathA)}</span>`:''}${x.pathB?`<span><strong>Mod B</strong>${esc(x.pathB)}</span>`:''}</div><details><summary>What should I do?</summary><div class="finding-detail"><div class="next-action">${esc(x.action||'Review this overlap with your intended load order.')}</div></div></details></div>`;list.appendChild(card);}}
function report(){return{schema:'paradox-doctor-compatibility-v1',generatedAt:new Date().toISOString(),game:state.game,loadOrder:state.loadOrder,modA:{files:state.a.size},modB:{files:state.b.size},conflicts:state.conflicts};}
function markdown(){const r=report();let s=`# Paradox Doctor compatibility report\n\n- Game: ${r.game==='hoi4'?'Hearts of Iron IV':'Victoria 3'}\n- Load order assumption: ${r.loadOrder}\n- Mod A files: ${r.modA.files}\n- Mod B files: ${r.modB.files}\n- Findings: ${r.conflicts.length}\n\n`;for(const x of r.conflicts)s+=`## ${x.title}\n- Severity: ${x.severity}\n- Category: ${x.category}\n- Confidence: ${x.confidence}\n${x.pathA?`- Mod A: ${x.pathA}\n`:''}${x.pathB?`- Mod B: ${x.pathB}\n`:''}\n${x.detail}\n\nNext: ${x.action||'Review this overlap.'}\n\n`;return s;}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);}
function clear(){state.filesA=[];state.filesB=[];state.a.clear();state.b.clear();state.conflicts=[];$('#modA').value='';$('#modB').value='';$('#statusA').textContent='Nothing selected';$('#statusB').textContent='Nothing selected';$('#compatResults').classList.add('hidden');updateReady();}
$('#modA').addEventListener('change',e=>select('a',[...e.target.files]));$('#modB').addEventListener('change',e=>select('b',[...e.target.files]));$('#compatRun').addEventListener('click',run);$('#compatClear').addEventListener('click',clear);$('#compatGame').addEventListener('change',e=>{state.game=e.target.value;localStorage.setItem('paradoxDoctorGameV4',state.game);if(state.conflicts.length){state.conflicts=[];$('#compatResults').classList.add('hidden');}});$('#loadOrder').addEventListener('change',e=>state.loadOrder=e.target.value);$$('[data-compat-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-compat-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.compatFilter;render();}));$('#compatSearch').addEventListener('input',e=>{state.search=e.target.value;render();});$('#compatJson').addEventListener('click',()=>download('paradox-doctor-compatibility.json',JSON.stringify(report(),null,2),'application/json'));$('#compatMd').addEventListener('click',()=>download('paradox-doctor-compatibility.md',markdown(),'text/markdown'));$('#compatCopy').addEventListener('click',async e=>{await navigator.clipboard.writeText(markdown());const t=e.target.textContent;e.target.textContent='Copied';setTimeout(()=>e.target.textContent=t,900);});
const saved=localStorage.getItem('paradoxDoctorGameV4');if(saved==='vic3'){state.game='vic3';$('#compatGame').value='vic3';}updateReady();
