'use strict';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const MAX_FILES = 3000;
const MAX_FILE_BYTES = 2.5 * 1024 * 1024;
const MAX_TOTAL_BYTES = 70 * 1024 * 1024;
const GAME_KEY = 'paradoxDoctorGameV4';
const supported = f => /\.(txt|yml|yaml|mod|gui|asset|csv|json)$/i.test(f.name);
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const state = {game:'hoi4',goodFiles:[],brokenFiles:[],good:new Map(),broken:new Map(),logText:'',changes:[],filter:'all',search:''};

function projectPath(file){const p=(file.webkitRelativePath||file.name).replaceAll('\\','/');const parts=p.split('/');return parts.length>1?parts.slice(1).join('/'):p;}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`;}
function braceDelta(text){let d=0,q=false,escp=false;for(let i=0;i<text.length;i++){const c=text[i];if(escp){escp=false;continue;}if(c==='\\'&&q){escp=true;continue;}if(c==='"'){q=!q;continue;}if(c==='#'&&!q){while(i<text.length&&text[i]!=='\n')i++;continue;}if(!q){if(c==='{')d++;else if(c==='}')d--;}}return d;}
function idSet(text,game){const ids=new Set();const patterns=game==='hoi4'?[/\bfocus\s*=\s*\{[\s\S]*?\bid\s*=\s*([A-Za-z0-9_.:-]+)/g,/\bid\s*=\s*([A-Za-z0-9_]+\.\d+)/g,/\bstate\s*=\s*\{[\s\S]*?\bid\s*=\s*(\d+)/g]:[/^\s*(je_[A-Za-z0-9_.:-]+)\s*=\s*\{/gm,/\bid\s*=\s*([A-Za-z0-9_]+\.\d+)/g,/^\s*(STATE_[A-Za-z0-9_]+)\s*=\s*\{/gm];for(const re of patterns)for(const m of text.matchAll(re))ids.add(m[1]);return ids;}
function pathRisk(path,game){const p=path.toLowerCase();const rules=game==='hoi4'?[[/history\/states\//,24,'HOI4 state file'],[/map\/strategicregions\//,22,'strategic region'],[/map\/definition\.csv$/,26,'province definition'],[/common\/national_focus\//,20,'focus tree'],[/events\//,14,'event script'],[/common\/(ideas|decisions|scripted_)/,12,'shared scripted content'],[/locali[sz]ation\//,9,'localization']]:[[/map_data\/state_regions\//,24,'state region'],[/common\/journal_entries\//,20,'journal entry'],[/events\//,16,'event script'],[/common\/scripted_/,14,'shared scripted content'],[/common\/(laws|buildings|production_methods)\//,12,'core game object'],[/localization\//,9,'localization']];for(const[r,s,label]of rules)if(r.test(p))return{score:s,label};return{score:5,label:'project file'};}
function changedRange(before,after){const a=before.split(/\r?\n/),b=after.split(/\r?\n/);let start=0;while(start<a.length&&start<b.length&&a[start]===b[start])start++;let ai=a.length-1,bi=b.length-1;while(ai>=start&&bi>=start&&a[ai]===b[bi]){ai--;bi--;}return{oldStart:start+1,oldEnd:Math.max(start+1,ai+1),newStart:start+1,newEnd:Math.max(start+1,bi+1),before:a,after:b,index:start};}
function snippet(lines,index){const s=Math.max(0,index-3),e=Math.min(lines.length,index+7);return lines.slice(s,e).map((x,i)=>`${String(s+i+1).padStart(4,' ')} | ${x}`).join('\n')||'(empty)';}
function logSignals(path,log){if(!log)return{score:0,reasons:[]};const low=log.toLowerCase(),p=path.toLowerCase(),base=p.split('/').pop();let score=0;const reasons=[];if(low.includes(p)){score+=45;reasons.push('error.log names this path');}else if(base&&low.includes(base)){score+=36;reasons.push('error.log names this file');}const category=pathRisk(path,state.game).label;if(category.includes('state')||category.includes('province')||category.includes('region')){if(/province|state|region|map/.test(low)){score+=12;reasons.push('log contains map/state errors');}}else if(category.includes('focus')){if(/focus|national_focus/.test(low)){score+=12;reasons.push('log contains focus errors');}}else if(category.includes('journal')||category.includes('event')){if(/journal|event|scope|event target/.test(low)){score+=12;reasons.push('log contains journal/event/scope errors');}}else if(category==='localization'){if(/locali[sz]ation|loc key|duplicate localization/.test(low)){score+=12;reasons.push('log contains localization errors');}}return{score,reasons};}
function suspicionLabel(score){return score>=55?'high':score>=28?'medium':'low';}

async function readFolder(files,target,statusEl){const usable=files.filter(supported).slice(0,MAX_FILES),total=usable.reduce((n,f)=>n+f.size,0);target.clear();if(total>MAX_TOTAL_BYTES)throw new Error(`Selection is ${formatBytes(total)}; reduce supported text files below ${formatBytes(MAX_TOTAL_BYTES)}.`);let n=0;for(const f of usable){if(f.size<=MAX_FILE_BYTES){try{target.set(projectPath(f),await f.text());}catch{}}n++;if(n%80===0){statusEl.textContent=`Reading ${n}/${usable.length} files…`;await new Promise(r=>setTimeout(r,0));}}statusEl.textContent=`${target.size} text files · ${formatBytes(total)}`;return usable;}
function setReady(){const ok=state.goodFiles.length&&state.brokenFiles.length;$('#regRunBtn').disabled=!ok;$('#regReady').textContent=ok?'Both versions are ready.':'Choose both project folders to compare.';$('#regReadyDetail').textContent=ok?(state.logText?'A fresh error.log will be used to rank changed files.':'Add the broken version error.log for stronger ranking.'):'Only supported text files are read.';}

async function loadGood(files){state.goodFiles=[...files];try{await readFolder(state.goodFiles,state.good,$('#goodStatus'));}catch(e){$('#goodStatus').textContent=e.message;state.goodFiles=[];}setReady();}
async function loadBroken(files){state.brokenFiles=[...files];try{await readFolder(state.brokenFiles,state.broken,$('#brokenStatus'));}catch(e){$('#brokenStatus').textContent=e.message;state.brokenFiles=[];}setReady();}
async function loadLog(file){if(!file)return;state.logText=await file.text();$('#regLogStatus').textContent=`${file.name} · ${formatBytes(file.size)}`;setReady();}

function buildChanges(){const paths=new Set([...state.good.keys(),...state.broken.keys()]),changes=[];for(const path of paths){const before=state.good.get(path),after=state.broken.get(path);let type;if(before===undefined)type='added';else if(after===undefined)type='removed';else if(before!==after)type='modified';else continue;let score=type==='modified'?14:type==='removed'?18:10;const reasons=[];const risk=pathRisk(path,state.game);score+=risk.score;reasons.push(risk.label);const ls=logSignals(path,state.logText);score+=ls.score;reasons.push(...ls.reasons);let range=null,removedIds=[];if(type==='modified'){range=changedRange(before,after);const bd=braceDelta(before),ad=braceDelta(after);if(ad!==0&&bd===0){score+=32;reasons.push(`brace balance changed from 0 to ${ad}`);}else if(ad!==bd){score+=12;reasons.push(`brace balance changed ${bd} → ${ad}`);}const oldIds=idSet(before,state.game),newIds=idSet(after,state.game);removedIds=[...oldIds].filter(x=>!newIds.has(x)).slice(0,8);if(removedIds.length){score+=Math.min(24,removedIds.length*6);reasons.push(`${removedIds.length} known IDs removed`);}const changedLines=Math.max(range.oldEnd-range.oldStart+1,range.newEnd-range.newStart+1);if(changedLines>80){score+=8;reasons.push('large edit');}}
if(type==='removed'){removedIds=[...idSet(before,state.game)].slice(0,8);if(removedIds.length){score+=Math.min(24,removedIds.length*6);reasons.push(`${removedIds.length} known IDs removed with file`);}}
changes.push({path,type,score,risk:suspicionLabel(score),reasons:[...new Set(reasons)],range,removedIds,before:before||'',after:after||'',logMatch:ls.score>0});}return changes.sort((a,b)=>b.score-a.score||a.path.localeCompare(b.path));}

function run(){if(!state.good.size||!state.broken.size)return;$('#regProgress').classList.remove('hidden');$('#regProgressBar').style.width='65%';$('#regProgressText').textContent='Comparing project paths and structural changes…';setTimeout(()=>{state.changes=buildChanges();$('#regProgressBar').style.width='100%';$('#regProgressText').textContent='Ranking regression suspects…';setTimeout(()=>{$('#regProgress').classList.add('hidden');renderSummary();},120);},80);}
function filtered(){const q=state.search.toLowerCase();return state.changes.filter(x=>state.filter==='all'||x.type===state.filter).filter(x=>!q||x.path.toLowerCase().includes(q)||x.reasons.join(' ').toLowerCase().includes(q));}
function renderSummary(){const c={modified:0,added:0,removed:0,log:0};for(const x of state.changes){c[x.type]++;if(x.logMatch)c.log++;}$('#changedCount').textContent=c.modified;$('#addedCount').textContent=c.added;$('#removedCount').textContent=c.removed;$('#logMatchedCount').textContent=c.log;$('#regResultsSubtitle').textContent=`${state.game==='hoi4'?'Hearts of Iron IV':'Victoria 3'} · ${state.changes.length} changed text files · ${state.logText?'error.log correlated':'no error.log'}`;const top=state.changes.filter(x=>x.risk!=='low').slice(0,5);$('#topSuspects').classList.toggle('hidden',!top.length);$('#topSuspectList').innerHTML=top.map(x=>`<li><strong>${esc(x.path)}</strong> — ${esc(x.reasons.slice(0,3).join(' · '))}</li>`).join('');$('#regResults').classList.remove('hidden');renderList();$('#regResults').scrollIntoView({behavior:'smooth',block:'start'});}
function renderList(){const list=$('#regList'),items=filtered();list.innerHTML='';$('#regEmpty').classList.toggle('hidden',items.length>0);for(const[xi,x]of items.entries()){const card=document.createElement('article');card.className=`reg-card ${x.risk}`;const range=x.range?`Changed around old ${x.range.oldStart}-${x.range.oldEnd} / new ${x.range.newStart}-${x.range.newEnd}`:x.type==='added'?'New file in broken version':'File removed from broken version';card.innerHTML=`<div class="reg-card-top"><div class="reg-rank"><span class="reg-rank-num">${xi+1}</span><div><div class="reg-path">${esc(x.path)}</div><div class="reg-meta">${esc(range)}</div></div></div><div class="reg-badges"><span class="change-badge">${x.type}</span><span class="risk-badge ${x.risk}">${x.risk} suspicion</span></div></div><div class="reg-reasons">${x.reasons.slice(0,6).map(r=>`<span>${esc(r)}</span>`).join('')}</div>${x.removedIds.length?`<p class="reg-change-summary">Removed identifiers: <code>${esc(x.removedIds.join(', '))}</code></p>`:''}${x.type==='modified'?`<details><summary>Preview first changed area</summary><div class="diff-grid"><div class="diff-pane"><strong>Working version</strong><pre>${esc(snippet(x.range.before,x.range.index))}</pre></div><div class="diff-pane"><strong>Broken version</strong><pre>${esc(snippet(x.range.after,x.range.index))}</pre></div></div></details>`:''}`;list.appendChild(card);} }
function report(){return{schema:'paradox-doctor-regression-v1',game:state.game,generatedAt:new Date().toISOString(),hasLog:!!state.logText,summary:{changed:state.changes.length},suspects:state.changes.map(({before,after,...x})=>x)};}
function md(){const r=report();let s=`# Paradox Doctor regression report\n\n- Game: ${state.game==='hoi4'?'Hearts of Iron IV':'Victoria 3'}\n- Generated: ${r.generatedAt}\n- error.log: ${r.hasLog?'included':'not included'}\n- Changed text files: ${r.suspects.length}\n\n`;r.suspects.forEach((x,i)=>{s+=`## ${i+1}. ${x.path}\n- Change: ${x.type}\n- Suspicion: ${x.risk}\n- Reasons: ${x.reasons.join('; ')}\n${x.removedIds?.length?`- Removed IDs: ${x.removedIds.join(', ')}\n`:''}\n`;});return s;}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);}
function feedback(){const top=state.changes.slice(0,5).map((x,i)=>`${i+1}. ${x.path} — ${x.risk} — ${x.reasons.slice(0,2).join(', ')}`).join('\n');const body=`Game: ${state.game}\n\nRegression Doctor top suspects:\n${top||'(no suspects)'}\n\nWas the real cause listed? What was wrong with the ranking?\n`;const url=`https://github.com/Reridy/paradox-doctor/issues/new?title=${encodeURIComponent('Regression Doctor feedback')}&body=${encodeURIComponent(body)}`;window.open(url,'_blank','noopener');}
function clearAll(){state.goodFiles=[];state.brokenFiles=[];state.good.clear();state.broken.clear();state.logText='';state.changes=[];$('#goodFolder').value='';$('#brokenFolder').value='';$('#regLogFile').value='';$('#goodStatus').textContent='Nothing selected';$('#brokenStatus').textContent='Nothing selected';$('#regLogStatus').textContent='No log selected';$('#regResults').classList.add('hidden');setReady();}

$('#regGame').value=localStorage.getItem(GAME_KEY)||'hoi4';state.game=$('#regGame').value;document.body.dataset.game=state.game;$('#regGame').addEventListener('change',e=>{state.game=e.target.value;document.body.dataset.game=state.game;localStorage.setItem(GAME_KEY,state.game);if(state.changes.length){state.changes=buildChanges();renderSummary();}});
$('#goodFolder').addEventListener('change',e=>loadGood([...e.target.files]));$('#brokenFolder').addEventListener('change',e=>loadBroken([...e.target.files]));$('#regLogFile').addEventListener('change',e=>loadLog(e.target.files[0]));$('#regRunBtn').addEventListener('click',run);$('#regClearBtn').addEventListener('click',clearAll);$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.change;renderList();}));$('#regSearch').addEventListener('input',e=>{state.search=e.target.value;renderList();});$('#regJsonBtn').addEventListener('click',()=>download(`paradox-doctor-regression-${state.game}.json`,JSON.stringify(report(),null,2),'application/json'));$('#regMdBtn').addEventListener('click',()=>download(`paradox-doctor-regression-${state.game}.md`,md(),'text/markdown'));$('#regCopyBtn').addEventListener('click',async e=>{await navigator.clipboard.writeText(md());const old=e.target.textContent;e.target.textContent='Copied';setTimeout(()=>e.target.textContent=old,900);});$('#regFeedbackBtn').addEventListener('click',feedback);setReady();
