const state={files:[],issues:[],logFile:null};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const fileInput=qs('#fileInput'),dropZone=qs('#dropZone'),scanFilesBtn=qs('#scanFilesBtn');
const logFileInput=qs('#logFileInput'),logDropZone=qs('#logDropZone'),logFileStatus=qs('#logFileStatus'),logInput=qs('#logInput');
qsa('.tab').forEach(tab=>tab.addEventListener('click',()=>{qsa('.tab').forEach(t=>t.classList.remove('active'));qsa('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');qs(`#${tab.dataset.tab}Panel`).classList.add('active')}));
fileInput.addEventListener('change',()=>setFiles([...fileInput.files]));
['dragenter','dragover'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add('dragover')}));
['dragleave','drop'].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove('dragover')}));
dropZone.addEventListener('drop',e=>setFiles([...e.dataTransfer.files]));
function setFiles(files){state.files=files.filter(f=>/\.(txt|yml|yaml|log)$/i.test(f.name));scanFilesBtn.disabled=!state.files.length;dropZone.querySelector('strong').textContent=state.files.length?`${state.files.length} file(s) selected`:'Drop HOI4 text files here'}

logFileInput.addEventListener('change',()=>loadLogFile(logFileInput.files[0]));
['dragenter','dragover'].forEach(ev=>logDropZone.addEventListener(ev,e=>{e.preventDefault();logDropZone.classList.add('dragover')}));
['dragleave','drop'].forEach(ev=>logDropZone.addEventListener(ev,e=>{e.preventDefault();logDropZone.classList.remove('dragover')}));
logDropZone.addEventListener('drop',e=>{const file=[...e.dataTransfer.files].find(f=>/\.(log|txt)$/i.test(f.name));if(file)loadLogFile(file);else logFileStatus.textContent='Please choose a .log or .txt file.'});
async function loadLogFile(file){if(!file)return;if(!/\.(log|txt)$/i.test(file.name)){logFileStatus.textContent='Please choose a .log or .txt file.';return}state.logFile=file;logFileStatus.textContent=`Loaded ${file.name} (${formatBytes(file.size)})`;logDropZone.querySelector('strong').textContent=file.name;logInput.value=await file.text();renderIssues(analyzeLog(logInput.value,file.name));}
function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`}

scanFilesBtn.addEventListener('click',scanFiles);
qs('#scanLogBtn').addEventListener('click',()=>renderIssues(analyzeLog(logInput.value,state.logFile?.name||'error.log')));
qs('#transformYearsBtn').addEventListener('click',transformYears);
qs('#copyYearsBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(qs('#yearOutput').value);qs('#copyYearsBtn').textContent='Copied!';setTimeout(()=>qs('#copyYearsBtn').textContent='Copy transformed text',1200)});
async function scanFiles(){const issues=[];for(const file of state.files){const text=await file.text();if(/\.ya?ml$/i.test(file.name))issues.push(...analyzeLocalization(text,file.name));if(/\.log$/i.test(file.name)||file.name==='error.log')issues.push(...analyzeLog(text,file.name));if(/\.txt$/i.test(file.name))issues.push(...analyzeScript(text,file.name));}renderIssues(issues)}
function issue(severity,title,file,line,explanation){return{severity,title,file,line,explanation}}
function analyzeLocalization(text,file){const out=[],lines=text.replace(/^\uFEFF/,'').split(/\r?\n/),seen=new Map();if(text.charCodeAt(0)!==0xFEFF)out.push(issue('warning','Missing UTF-8 BOM',file,1,'HOI4 localization files are commonly expected to use UTF-8 with BOM. Re-save the file with UTF-8 BOM if the game does not load it correctly.'));if(lines[0]&&!/^\s*l_[a-z_]+:\s*$/i.test(lines[0]))out.push(issue('error','Missing or malformed language header',file,1,'Localization files should begin with a language header such as l_english: or l_korean:.'));
lines.forEach((raw,i)=>{const n=i+1,line=raw.trim();if(!line||line.startsWith('#')||/^l_[a-z_]+:\s*$/i.test(line))return;const m=raw.match(/^\s*([^\s:#]+)\s*:\s*(\d+)?\s*"(.*)"\s*(?:#.*)?$/);if(!m){if(/^[^#\s][^:]*\s+"/.test(line)||(!line.includes(':')&&line.includes('"')))out.push(issue('error','Malformed localization entry',file,n,'This line does not match the expected key:0 "Text" localization format. Check the colon, version number and quotes.'));else if(line.includes(':')&&!/".*"/.test(line))out.push(issue('warning','Localization value may be unquoted',file,n,'Localization text should normally be wrapped in double quotes.'));return}const key=m[1];if(seen.has(key))out.push(issue('error',`Duplicate localization key: ${key}`,file,n,`This key was already declared on line ${seen.get(key)} in the same file. Rename or remove one declaration.`));else seen.set(key,n);const quoteCount=(raw.match(/"/g)||[]).length;if(quoteCount%2!==0)out.push(issue('error','Unbalanced quotes',file,n,'The localization value appears to contain an unmatched double quote.'));});return out}
function analyzeLog(text,file){const out=[];text.split(/\r?\n/).forEach((raw,i)=>{if(!raw.trim())return;const lower=raw.toLowerCase(),n=i+1;if(lower.includes('duplicate localization found')){const key=(raw.match(/key:\s*([^,\s]+)/i)||[])[1];out.push(issue('error',key?`Duplicate localization: ${key}`:'Duplicate localization',file,n,'The same localization key is declared more than once. Search the referenced key across your localization files and keep only the intended definition.'));}else if(lower.includes('unexpected token'))out.push(issue('error','Unexpected token',file,n,'The parser encountered syntax it did not expect. Inspect nearby braces, equals signs, identifiers and quotes.'));else if(lower.includes('unknown effect')||lower.includes('unknown trigger'))out.push(issue('error','Unknown script command',file,n,'The game does not recognize an effect or trigger on this line. Check spelling, game version, scope and required DLC/mod dependencies.'));else if(lower.includes('could not find')||lower.includes('not found'))out.push(issue('warning','Missing reference',file,n,'A referenced object or file could not be resolved. Verify the identifier, path and load order.'));else if(/error|exception|invalid/.test(lower))out.push(issue('warning','Unclassified engine error',file,n,raw.replace(/^.*?:\s*/, '').slice(0,240)));});if(text.trim()&&!out.length)out.push(issue('info','No known patterns detected',file,1,'The log contains text, but this alpha scanner did not recognize a supported error pattern yet.'));return out}
function analyzeScript(text,file){const out=[],lines=text.split(/\r?\n/),ids=new Map(),idPattern=/^\s*(?:id|focus|idea|event)\s*=\s*([A-Za-z0-9_.:-]+)\s*(?:#.*)?$/i;lines.forEach((raw,i)=>{const n=i+1,m=raw.match(idPattern);if(m){const id=m[1];if(ids.has(id))out.push(issue('warning',`Possible duplicate ID: ${id}`,file,n,`The same simple ID assignment appeared on line ${ids.get(id)}. This heuristic can produce false positives across different scopes.`));else ids.set(id,n)}const years=[...raw.matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(x=>Number(x[1]));years.forEach(y=>{if(y<1936&&/\byear\s*=|\bdate\s*[<>=]/i.test(raw))out.push(issue('info',`Suspicious historical year: ${y}`,file,n,'This may be intentional. If your mod shifts the timeline, review whether this date should be transformed.'))});});return out}
function transformYears(){const input=qs('#yearInput').value,offset=Number(qs('#yearOffset').value)||0,min=Number(qs('#yearMin').value)||0,max=Number(qs('#yearMax').value)||9999;const output=input.replace(/\b(\d{4})\b/g,(full,y,idx,str)=>{const year=Number(y);if(year<min||year>max)return full;const context=str.slice(Math.max(0,idx-24),idx+12);if(!/(year\s*=|date\s*[<>=]|\b\d{4}[.\/-])/i.test(context))return full;return String(year+offset)});qs('#yearOutput').value=output;qs('#copyYearsBtn').disabled=!output}
function renderIssues(issues){state.issues=issues;const box=qs('#results'),list=qs('#resultList');box.classList.remove('hidden');list.innerHTML='';const counts={error:0,warning:0,info:0};issues.forEach(x=>counts[x.severity]++);const score=Math.max(0,100-counts.error*12-counts.warning*4-counts.info);qs('#healthScore').textContent=`${score} / 100`;qs('#errorCount').textContent=`${counts.error} error${counts.error===1?'':'s'}`;qs('#warningCount').textContent=`${counts.warning} warning${counts.warning===1?'':'s'}`;qs('#infoCount').textContent=`${counts.info} note${counts.info===1?'':'s'}`;if(!issues.length){list.innerHTML='<article class="result-card"><div class="result-title">No supported problems detected</div><p>This does not guarantee the mod is error-free, but the current alpha checks passed.</p></article>';return}issues.forEach(x=>{const card=document.createElement('article');card.className='result-card';card.innerHTML=`<div class="result-top"><span class="result-title"></span><span class="badge ${x.severity}">${x.severity}</span></div><div class="result-meta"></div><p></p>`;card.querySelector('.result-title').textContent=x.title;card.querySelector('.result-meta').textContent=`${x.file}:${x.line}`;card.querySelector('p').textContent=x.explanation;list.appendChild(card)});box.scrollIntoView({behavior:'smooth',block:'start'})}
